from __future__ import annotations

from pathlib import Path


def bytes_to_c_header(byte_data: bytes, array_name: str, output_path: str | Path) -> Path:
    """Formats raw binary into a static const C-array header for embedded firmware."""
    target = Path(output_path).resolve()
    target.parent.mkdir(parents=True, exist_ok=True)

    hex_elements = [f"0x{byte:02x}" for byte in byte_data]
    lines = []
    for i in range(0, len(hex_elements), 12):
        lines.append("    " + ", ".join(hex_elements[i : i + 12]))

    array_body = ",\n".join(lines)

    header_content = f"""/* Auto-generated by ResQVision Autonomy Exporter. Do not edit manually. */
#ifndef RESQ_SAFETY_MODEL_H
#define RESQ_SAFETY_MODEL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

const unsigned int {array_name}_len = {len(byte_data)};
const uint8_t {array_name}[] __attribute__((aligned(4))) = {{
{array_body}
}};

#ifdef __cplusplus
}}
#endif

#endif /* RESQ_SAFETY_MODEL_H */
"""
    target.write_text(header_content, encoding="utf-8")
    return target