"""added_lecture_content_and_quizzes

Revision ID: c03b91722ba8
Revises: d5a921955c7f
Create Date: 2026-04-11 12:39:26.307454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c03b91722ba8'
down_revision: Union[str, Sequence[str], None] = 'd5a921955c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lecture_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lecture_id', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('last_watched_second', sa.Integer(), nullable=True),
    sa.Column('notes_read', sa.Boolean(), nullable=True),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lectures', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('lectures', sa.Column('quiz_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lectures', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.drop_column('lectures', 'content_url')
    op.drop_column('lectures', 'duration_seconds')
    op.drop_column('lectures', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('content_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('lectures', 'estimated_minutes')
    op.drop_column('lectures', 'quiz_data')
    op.drop_column('lectures', 'video_url')
    op.drop_table('user_lecture_progress')
    # ### end Alembic commands ###
